# -*- coding: utf-8 -*-
"""Python_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Bt2Q21snuCMOmvmydsl_y4mMQfirXFV

##Float is Weird
Komputer pada dasarnya melakukan penjumlahan, dan float tidak dapat direpresentasikan secara tepat di dunia biner.
"""

print(1.1 + 2.2 == 3.3000000000000003)

print(1.1 + 2.2)

# Solution

a = 1.1
b = 2.2
tolerance = 0.000001
print(abs(3.3 - (a + b)) < tolerance)

"""## Conditional Expression"""

a = 3
b = 4
print(a<b)
print(a>b)
print(a<=b)
print(a>=b)
print(a==b)
print(a!=b)

"""## If Else Statement"""

namaku = "Zain"
umurku = 19
laki = True

if namaku == "Akira" or namaku == "Jamal":
  print("Namaku Akira atau Jamal")
else:
  print("Namaku bukan Akira dan bukan Jamal")

if namaku == "Akira":
  print("Namaku Akira")
elif namaku == "Jamal":
  print("Namaku Jamal")
else:
  print("Namaku bukan Akira dan bukan Jamal")

"""##Truthy and Falsy"""

#Var is Truthy, None is Falsy
if 5:
  print("Halo")
else:
  print("Byee")

if None:
  print("Nonee👍")
else:
  print("Not none👌👏👏👏")

"""## Logical Operators"""

namaku = "Akira"
umurku = 19
laki = True

#     True                True
if namaku == "Akira" and laki:
  print("Akira lakik")
else:
  print("Bukan Akira atau Bukan Laki atau Bukan dua-duanya")

# And
# True and True = True
# True and False = False
# False and False = False

# Or
# True or True = True
# True or False = True
# False or False = False

"""## Input"""

# Selalu jadi string\
Nama = input("Masukan namamu : ")
while Nama == "":
  Nama = input("Masukkan namamu : ")
tahun_kelahiran = int(input("Masukkan tahun kelahiran : "))
tahun_sekarang = 2022

print("Namaku", Nama)
print("Umurku", tahun_sekarang - tahun_kelahiran)

"""##Assignment Operators"""

a = 0
a = a + 1
a += 1
a //= 2
print(a)

"""##Types of Loops"""

a = []
total = 0

# range(start, stop, step)
# for i in range(3,10,3):
for i in range(10):
  #a[i] = i
  a.append(i)
print(a)

for i in range(len(a)):
  a[i] += 1
print(a)

# for huruf in "Kalimat":
#   print(huruf)

s = "kalimat"
print (s.count("a"))
c = s.count("a")
for i in range(c):
  print("HI")

daftarteman = ["Andi", "Zain", "Jamal", "Rosa"]

for teman in daftarteman:
  print(teman)

# print(a)

tahun = 2000
while tahun != 2000:
  tahun += 1
  print(tahun)

lapar = True
perut = 0
while lapar:
  perut += 1
  print(perut)
  if perut == 10:
    lapar = False

"""## Nested Loop"""

for j in range(5):
  for i in range(3):
    print(i, j)

"""## Nested List and Nested Loop"""

a = [[1,2,3],
     [4,5,6],
     [7,8,9]]
# print(a[0][0])

for i in range(3):
  for j in range(3):
    print(a[i][j])

"""## Function and Lambda Function"""

def volume(luas, tinggi):
  return luas*tinggi

# print(volume(20, 10))

a = lambda a,b:a+b
print(a(7,10))

"""## Sedikit OOP"""

class orang:
  def __init__(self):
    self.nama = "Akira"
    self.umur = 19
    self.laki = True

a = orang()
print(a.nama)