# -*- coding: utf-8 -*-
"""Python_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nkwNSndGGeTQ_-F3Ci7s9MoDTgKbh8mO

##Print
"""

a = 3.14159265
b = 3.145231
formatted_a = "{:.3f}".format(a)
formatted_b = "{:.2f}".format(b)
print(formatted_a)
print(formatted_b)

print("""Hello Putra
Ucok""")
print('Hello Della')

"""##Sequence"""

print("   /|")
print("  / |")
print(" /  |")
print("/___|")

"""##Variables and Datatypes"""

# String
namaku = 'Nama'
namaku = """Putra Ajah
Begitulah"""

# Integer
umurku = 18

tahunKelahiran = 2004
tahunSekarang = 2023

# Boolean
perempuan = True

# Float
tinggi = 1.48

# Complex number
angka = 2+2j

# Tuple
mytuple = (1,2,3)

print(type(perempuan))
print(type(tinggi))
print(type(angka))

"""##Jenis2 Format"""

print("Halo, namaku " + namaku)
print(umurku + umurku)
print("Umurku "+ umurku)

print("Halo, namaku", namaku)
print("Umurku", umurku)

# %-Formatting
print("Halo, namaku %s.\nUmurku %s. %s umur %s" % (namaku, umurku, namaku, umurku))

# str.format()
# 0 itu pertama, 1 itu kedua
print("Halo, namaku {nama}.\nUmurku {umur}.\n{nama} umur {umur}".format(nama = namaku, umur = umurku))

# f-String
print(f"Halo, namaku {namaku}.\nUmurku {umurku}.\n{namaku} umur {umurku}")
print(f"Halo, namaku {namaku}.\nUmurku {umurku}.\n{namaku} umur {tahunSekarang - tahunKelahiran}")
print(f"{{{tahunSekarang - tahunKelahiran}}}")

"""##Operation"""

a = 4
b = 3.0
print(a + b)
print(a * b)
print(a - b)
print(a % b)
print(a ** b)
print(pow(a,b))
print(abs(-105))
print(max(10,3,4,5,6,10))
print(min(3,4,5,6,10))

"""##List"""

a = ["A", "B", "C", "D"]
#     0    1    2    3
b = [ 1, 2, 3 ]
c = [True, False, True]
e = "abcdefghijklmnop"
print(e[::-3])
print(b)
print(a[1])
print(len(a))
print(a[2])
print(a[0:5])
print(a[1:])
print(a[:3])

a = ["A", "B", "C", "D", "B"]
    # 0    1    2    3
b = [ 1, 2, 3 ]
d = [ 1, 2, 3 ]
c = [True, False, True]

#a.extend(b + c)
#a.append("E")
#a.insert(0, "E")
a.remove("B")
print(a)

#a.clear()
ygkeluar = a.pop(1)
print(ygkeluar)
print(a)

print(a.index("B"))
# print(a.count("B"))
# a.sort()
#a.reverse()

# Tuple - Gak bisa berubah, gak bisa nambah, ada order
a = (1,2,3)
print(a)
print(type(a))

# Set - Gak bisa diubah, bisa nambah, gak ada order, no duplikat
b = {1,3,2,2,3,4}
d = {7, 8}
print(b)
print(type(b))

# List - Bisa ubah, bisa nambah, order, duplikat
c = [1,2,3]
print(c)
print(type(c))

# Set - Bisa diubah, bisa nambah, gak ada order, no duplikat
#          Key : Value
kamus = {"nama": "Jamal",
         "umur":19,
         "laki":True,
         "teman": ["Gugun", "Janico", "Abdul"]
         }
kamus["nama"] = "Zain"
print(kamus["teman"][0])
print(type(kamus))

# Nama harus unik
# Bisa ada parameter atau enggak
# Bisa return atau enggak
def sapasalam(nama):
  print("Haloow", nama)
  print("Babaii", nama)

sapasalam("Jamal")

def pangkattiga(num):
  return num * num * num

a = 6
b = pangkattiga(a)
print(b)

print(1.1 + 2.2 == 3.3)